vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        post_image:
            uri_prefix: /uploads/posts
            upload_destination: '%kernel.project_dir%/public/uploads/posts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer